resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt-get update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt install nodejs 
            - sudo npm install @neuralegion/nexploit-cli -g
            - |
                  SCAN_ID=$(nexploit-cli scan:run                                                \
                  --name "💎 Broken Crystals for JFrog" \
                  --crawler https://brokencrystals.com                                         \
                  --token qmfz1ab.nexa.g8dpu2y00u3jenmn3hlortbtuv3sbeuz)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
              nexploit-cli scan:polling               \
                --interval 10s                        \
                --timeout 12m                         \
                --token qmfz1ab.nexa.g8dpu2y00u3jenmn3hlortbtuv3sbeuz  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
