resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            - sudo chmod +x install.sh
            - ./install.sh
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - |
                SCAN_ID=$(nexploit-cli scan:run                                                \
                  --name "💎 Broken Crystals for a #${res_jfrognexploit_commitSha} #${run_id}" \
                  --crawler https://brokencrystals.com                                         \
                  --token $int_Nexploit_NEXPLOIT_TOKEN)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 12m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
