resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt-get update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - sudo  apt-get install nodejs=14.9.0
            - sudo  apt-get install npm=4.0.0
            - npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - SCAN_ID=$(nexploit-cli scan:run --name "💎 Broken Crystals JFrog" --crawler https://brokencrystals.com --token $NEXPLOIT_TOKEN)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
              nexploit-cli scan:polling               \
                --interval 10s                        \
                --timeout 12m                         \
                --token $NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
