resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install -y nodejs
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - |
              SCAN_ID=$(nexploit-cli scan:run \
                --token $int_Nexploit_NEXPLOIT_TOKEN      \
                --api https://app.neuralegion.com         \
                --bus amqps://amq.app.neuralegion.com:5672 \
                --name "💎 Broken Crystals"               \
                --crawler https://brokencrystals.com)      
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
              nexploit-cli scan:polling               \
                --interval 10s                        \
                --timeout 12m                         \
                --token qmfz1ab.nexa.g8dpu2y00u3jenmn3hlortbtuv3sbeuz  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
