resources:
  - name: JFrogNeuraLegion
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: NeuraLegion/jfrog-example

pipelines:
  - name: neuralegion
    steps:
      - name: neuralegion
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: JFrogNeuraLegion
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install -y nodejs
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - |
              SCAN_ID=$(nexploit-cli scan:run \
                --token $int_Nexploit_NEXPLOIT_TOKEN      \
                --api https://app.neuralegion.com         \
                --bus amqps://amq.app.neuralegion.com:5672 \
                --name "💎 Broken Crystals scan without repeater"               \
                --crawler https://brokencrystals.com)      
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID\n"
            - printf "Wait for issues ⏳\n"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
