resources:
  - name: jfrog-example
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example
pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
           execution:[
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - sudo apt install nodejs npm
            - sudo apt install --fix-broken
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - SCAN_ID=$(nexploit-cli scan:run --name "💎 Broken Crystals for a #${res_jfrognexploit_commitSha} #${run_id}" --crawler https://brokencrystals.com --token $int_Nexploit_NEXPLOIT_TOKEN)        
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
